# GreenFarm source builder
import re
NAV=[("index","Home"),("dashboard","Dashboard"),("crops","Crops"),("livestock","Livestock"),("activities","Activities"),("analytics","Analytics"),("reports","Reports"),("farm","Workspace"),("admin","Admin")]
def shell(page,title,body,extra_js=""):
    links="".join(f'<a href="{p}.html"{" class="active" aria-current="page" if p==page else ""}>{n}</a>' for p,n in NAV)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#043a24"><meta name="description" content="{title} | GreenFarm Smart Digital Agriculture"><title>{title} | GreenFarm</title><link rel="stylesheet" href="assets/greenfarm.css"></head><body>
<header class="inst-header"><div class="inst-inner"><div class="inst-left"><img class="inst-logo" src="https://agritech.tnau.ac.in/ta/pdf/images/TNAU.jpg" alt="Tamil Nadu Agricultural University"><div class="inst-copy"><div class="inst-title">TAMIL NADU AGRICULTURAL UNIVERSITY</div><div class="inst-tamil">தமிழ்நாடு வேளாண்மைப் பல்கலைக்கழகம்</div><div class="inst-address">Agricultural College &amp; Research Institute · Vazhavachanur · Tamil Nadu</div></div></div><div class="gf-project"><div class="gf-project-name">GreenFarm</div><div class="gf-project-sub">SMART DIGITAL AGRICULTURE</div><div class="gf-project-meta">TNAU · AC&amp;RI · Vazhavachanur</div></div></div></header>
<nav class="gf-nav" aria-label="Main navigation"><div class="container"><div class="nav-links">${links}</div></div></nav>
<main>{body}</main><footer class="gf-footer"><div class="container"><div><strong>🌱 GreenFarm</strong><p>Smart Digital Agriculture · TNAU AC&amp;RI Vazhavachanur</p></div><div><a href="index.html">Home</a><a href="reports.html">Reports</a><a href="farm.html#backup">Backup</a></div><small>© 2026 GreenFarm · Browser storage only</small></div></footer><script src="assets/app.js"></script>{extra_js}</body></html>'''
def standard(key,title,kicker,desc,icon,empty,button):
    return shell(key,title,f'''<div class="page"><section class="page-hero"><small>{kicker}</small><h1>{title}</h1><p>{desc}</p></section><section class="workspace-card"><div class="empty-icon">{icon}</div><h2>{empty}</h2><p>GreenFarm shows only records entered by you. No sample farm figures are used.</p><div class="actions"><a class="btn2" href="{button}">Open Workspace →</a><button class="btn2 alt" onclick="window.print()">Print page</button></div></section><div class="info-grid"><div class="info"><strong>Real data only</strong><span>Your records are stored locally in this browser.</span></div><div class="info"><strong>Responsive</strong><span>Optimised for desktop, tablet and mobile.</span></div><div class="info"><strong>Backup ready</strong><span>Use Workspace → Backup to export JSON.</span></div></div></div>''')
pages=[("crops","Crop Management","CROPS","Track crops, fields, varieties and growth stages.","🌾","No crop records yet","farm.html#crops"),("livestock","Livestock","LIVESTOCK","Manage animal groups, health observations and care notes.","🐄","No livestock records yet","farm.html#livestock"),("activities","Farm Activities","OPERATIONS","Plan irrigation, scouting, harvest and daily operations.","📅","No activities yet","farm.html#irrigation"),("analytics","Analytics","PERFORMANCE","Review indicators calculated from your own farm records.","📈","No analytics yet","farm.html#harvest"),("reports","Reports","PRINT & SHARE","Prepare clean print-ready summaries from your farm data.","🧾","No report data yet","farm.html#reports"),("admin","Admin","SETTINGS","Manage farm profile, backup and local workspace settings.","⚙️","Workspace settings","farm.html#backup")]
for p in pages: open(p[0]+".html","w").write(standard(*p))
dashboard_body='''<div class="page dashboard-page"><section class="page-hero"><div><small>FARM OVERVIEW</small><h1>Dashboard</h1><p>One clean view of your GreenFarm workspace, records and next actions.</p></div></section><section class="dashboard-stats" aria-label="Farm record summary"><div class="dashboard-stat"><div class="ds-icon">🌾</div><strong id="dashCrops">0</strong><span>Crop records</span></div><div class="dashboard-stat"><div class="ds-icon">🐄</div><strong id="dashLivestock">0</strong><span>Livestock records</span></div><div class="dashboard-stat"><div class="ds-icon">💧</div><strong id="dashIrrigation">0</strong><span>Irrigation records</span></div><div class="dashboard-stat"><div class="ds-icon">📊</div><strong id="dashTotal">0</strong><span>Total records</span></div></section><div class="dashboard-grid"><section class="dashboard-panel"><h2>Quick workspace</h2><div class="quick-grid"><a class="quick-card" href="farm.html#crops">🌾<strong>Crop</strong><span>Add and manage crop records</span></a><a class="quick-card" href="farm.html#livestock">🐄<strong>Livestock</strong><span>Track animal groups and care</span></a><a class="quick-card" href="farm.html#weather">🌦️<strong>Weather</strong><span>Record local observations</span></a><a class="quick-card" href="farm.html#soil">🌱<strong>Soil</strong><span>Store soil test information</span></a><a class="quick-card" href="farm.html#irrigation">💧<strong>Irrigation</strong><span>Plan and record water use</span></a><a class="quick-card" href="farm.html#reports">🧾<strong>Reports</strong><span>Print or save reports as PDF</span></a></div></section><aside class="dashboard-panel"><h2>Workspace status</h2><div class="status-list"><div class="status-row"><span>Storage</span><strong>Browser LocalStorage</strong></div><div class="status-row"><span>Backend</span><strong>Not required</strong></div><div class="status-row"><span>Backup</span><strong>JSON export</strong></div><div class="status-row"><span>Devices</span><strong>Mobile + Desktop</strong></div></div><div class="actions" style="margin-top:16px"><a class="btn2" href="farm.html">Open Workspace →</a></div></aside></div></div>'''
dashjs='''<script>(function(){try{const d=JSON.parse(localStorage.getItem("greenfarm.v2")||"null")||{records:{}};const r=d.records||{};const keys=["crops","livestock","weather","soil","irrigation","ipm","harvest","finance","inventory"];const n=k=>Array.isArray(r[k])?r[k].length:0;document.getElementById("dashCrops").textContent=n("crops");document.getElementById("dashLivestock").textContent=n("livestock");document.getElementById("dashIrrigation").textContent=n("irrigation");document.getElementById("dashTotal").textContent=keys.reduce((s,k)=>s+n(k),0)}catch(e){}})();</script>'''
open("dashboard.html","w").write(shell("dashboard","Dashboard",dashboard_body,dashjs))
cards=[("🌾","Crops","Fields, varieties and growth stages.","crops.html"),("🐄","Livestock","Animal groups and health records.","livestock.html"),("📅","Activities","Daily farm operations and tasks.","activities.html"),("📈","Analytics","Insights from your own records.","analytics.html"),("💧","Irrigation & IPM","Water management and pest scouting.","farm.html#irrigation"),("💰","Finance","Income, expenses and balances.","farm.html#finance")]
cd="".join(f'<a class="card" href="{u}"><div class="icon">{i}</div><h3>{t}</h3><p>{d}</p></a>' for i,t,d,u in cards)
home=f'''<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">TNAU · AC&amp;RI Vazhavachanur</span><h1>Smarter Farming. <span>Better Decisions.</span></h1><p>GreenFarm organises crops, livestock, activities, finances and reports in one responsive workspace for desktop and mobile.</p><div class="hero-actions"><a class="btn btn-gold" href="farm.html">Open Workspace</a><a class="btn btn-light" href="dashboard.html">View Dashboard</a></div></div><div class="hero-panel"><strong>Farm workspace</strong><div class="panel-grid"><div class="metric"><small>Modules</small><strong>13</strong></div><div class="metric"><small>Storage</small><strong>Local</strong></div><div class="metric"><small>Backup</small><strong>JSON</strong></div><div class="metric"><small>Reports</small><strong>PDF</strong></div></div></div></div></section><div class="container"><div class="snapshot-grid"><div class="snap"><strong>13</strong><span>Farm modules</span></div><div class="snap"><strong>Local</strong><span>Private storage</span></div><div class="snap"><strong>Mobile + PC</strong><span>Responsive UI</span></div><div class="snap"><strong>JSON</strong><span>Backup ready</span></div></div></div><section class="section"><div class="container"><div class="section-head"><span class="kicker">WORKSPACE</span><h2>Everything your farm needs</h2><p>Open a module and start recording your real farm information.</p></div><div class="modules">${cd}</div></div></section><section class="cta"><div class="container cta-box"><div><h2>Start recording your farm</h2><p>Your records stay in this browser until you export or clear them.</p></div><a class="btn btn-gold" href="farm.html">Open Workspace →</a></div></section>'''
open("index.html","w").write(shell("index","Smart Digital Agriculture",home))
s=open("farm.html",encoding="utf-8").read(); m=re.search(r'<main class="farm-shell">.*?</main>',s,re.S)
if not m: raise SystemExit("farm main not found")
toast=re.search(r'<div class="toast"[^>]*>.*?</div>',s,re.S)
tail=toast.group(0) if toast else '<div class="toast" id="toast" role="status" aria-live="polite"></div>'
open("farm.html","w",encoding="utf-8").write(shell("farm","Farm Workspace",m.group(0)+tail,'<script src="assets/farm.js"></script>'))
open("auth.html","w").write(shell("auth","Farm Access",'<div class="auth"><div class="auth-card"><span class="kicker">FARM ACCESS</span><h1>Your farm, on this device</h1><p>GreenFarm uses browser storage. No server account is required for this local workspace.</p><a class="btn2" href="farm.html">Open Workspace →</a></div></div>'))
