# GreenFarm clean responsive page builder
import re
NAV=[("index","Home"),("dashboard","Dashboard"),("crops","Crops"),("livestock","Livestock"),("activities","Activities"),("analytics","Analytics"),("reports","Reports"),("farm","Workspace"),("admin","Admin")]
def shell(page,title,body,extra=""):
    links="".join(f'<a href="{p}.html"{" class="active" aria-current="page" if p==page else ""}>{n}</a>' for p,n in NAV)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#063b25"><title>{title} | GreenFarm</title><link rel="stylesheet" href="assets/greenfarm.css"></head><body>
<header class="inst-header"><div class="inst-inner"><div class="inst-left"><img class="inst-logo" src="https://agritech.tnau.ac.in/ta/pdf/images/TNAU.jpg" alt="TNAU logo"><div><div class="inst-title">TAMIL NADU AGRICULTURAL UNIVERSITY</div><div class="inst-tamil">தமிழ்நாடு வேளாண்மைப் பல்கலைக்கழகம்</div><div class="inst-address">Agricultural College &amp; Research Institute · Vazhavachanur</div></div></div><div class="gf-project"><div class="gf-project-name">GreenFarm</div><div class="gf-project-sub">SMART DIGITAL AGRICULTURE</div><div class="gf-project-meta">TNAU · AC&amp;RI · Vazhavachanur</div></div></div></header>
<nav class="gf-nav"><div class="container"><button class="dashboard-nav-toggle" onclick="this.nextElementSibling.classList.toggle('dashboard-nav-open')" aria-label="Open navigation">☰ <span>Menu</span></button><div class="nav-links">${links}</div></div></nav><main>{body}</main><footer class="gf-footer"><div class="container"><div><strong>🌱 GreenFarm</strong><p>Smart Digital Agriculture · Local browser workspace</p></div><div><a href="index.html">Home</a> <a href="reports.html">Reports</a> <a href="farm.html#backup">Backup</a></div></div></footer><script src="assets/app.js"></script>{extra}</body></html>'''
def standard(key,title,kicker,desc,icon,empty,button):
    return shell(key,title,f'''<div class="page"><section class="page-hero"><small>{kicker}</small><h1>{title}</h1><p>{desc}</p></section><section class="workspace-card"><div class="empty-icon">{icon}</div><h2>{empty}</h2><p>Add your own records in Workspace. GreenFarm does not use sample farm data.</p><div class="actions"><a class="btn2" href="{button}">Open Workspace →</a><button class="btn2 alt" onclick="window.print()">Print</button></div></section><div class="info-grid"><div class="info"><strong>Private</strong><span>Records stay in this browser.</span></div><div class="info"><strong>Responsive</strong><span>Designed for desktop and mobile.</span></div><div class="info"><strong>Backup</strong><span>Export JSON from Workspace.</span></div></div></div>''')
pages=[("crops","Crop Management","CROPS","Track fields, crops, varieties and growth.","🌾","No crop records yet","farm.html#crops"),("livestock","Livestock","LIVESTOCK","Track animals, groups and care notes.","🐄","No livestock records yet","farm.html#livestock"),("activities","Activities","OPERATIONS","Keep daily farm operations organised.","📅","No activities yet","farm.html#irrigation"),("analytics","Analytics","PERFORMANCE","See insights from your own farm records.","📈","No analytics yet","farm.html#harvest"),("reports","Reports","REPORTS","Create clean summaries for print or PDF.","🧾","No report data yet","farm.html#reports"),("admin","Admin","SETTINGS","Manage profile, backup and local settings.","⚙️","Workspace settings","farm.html#backup")]
for p in pages: open(p[0]+".html","w").write(standard(*p))
dash='''<div class="page dashboard-page"><section class="page-hero"><small>FARM OVERVIEW</small><h1>Dashboard</h1><p>Your records, quick actions and workspace status.</p></section><section class="dashboard-stats"><div class="dashboard-stat"><div class="ds-icon">🌾</div><strong id="dashCrops">0</strong><span>Crops</span></div><div class="dashboard-stat"><div class="ds-icon">🐄</div><strong id="dashLivestock">0</strong><span>Livestock</span></div><div class="dashboard-stat"><div class="ds-icon">💧</div><strong id="dashIrrigation">0</strong><span>Irrigation</span></div><div class="dashboard-stat"><div class="ds-icon">📊</div><strong id="dashTotal">0</strong><span>Total records</span></div></section><div class="dashboard-grid"><section class="dashboard-panel"><h2>Quick access</h2><div class="quick-grid"><a class="quick-card" href="farm.html#crops">🌾<strong>Crop</strong><span>Manage crop records</span></a><a class="quick-card" href="farm.html#livestock">🐄<strong>Livestock</strong><span>Manage animal records</span></a><a class="quick-card" href="farm.html#weather">🌦️<strong>Weather</strong><span>Record observations</span></a><a class="quick-card" href="farm.html#soil">🌱<strong>Soil</strong><span>Store soil tests</span></a><a class="quick-card" href="farm.html#irrigation">💧<strong>Irrigation</strong><span>Manage water use</span></a><a class="quick-card" href="farm.html#reports">🧾<strong>Reports</strong><span>Print or save PDF</span></a></div></section><aside class="dashboard-panel"><h2>Workspace</h2><div class="status-list"><div class="status-row"><span>Storage</span><strong>Browser</strong></div><div class="status-row"><span>Backend</span><strong>None</strong></div><div class="status-row"><span>Backup</span><strong>JSON</strong></div><div class="status-row"><span>View</span><strong>Desktop + Mobile</strong></div></div><div class="actions"><a class="btn2" href="farm.html">Open Workspace →</a></div></aside></div></div>'''
dashjs='''<script>(function(){try{const d=JSON.parse(localStorage.getItem("greenfarm.v2")||"null")||{records:{}};const r=d.records||{};const n=k=>Array.isArray(r[k])?r[k].length:0;const ks=["crops","livestock","weather","soil","irrigation","ipm","harvest","finance","inventory"];document.getElementById("dashCrops").textContent=n("crops");document.getElementById("dashLivestock").textContent=n("livestock");document.getElementById("dashIrrigation").textContent=n("irrigation");document.getElementById("dashTotal").textContent=ks.reduce((s,k)=>s+n(k),0)}catch(e){}})();</script>'''
open("dashboard.html","w").write(shell("dashboard","Dashboard",dash,dashjs))
cards=[("🌾","Crops","Fields and growth.","crops.html"),("🐄","Livestock","Animals and care.","livestock.html"),("📅","Activities","Daily operations.","activities.html"),("📈","Analytics","Farm insights.","analytics.html"),("💧","Irrigation","Water management.","farm.html#irrigation"),("💰","Finance","Income and expenses.","farm.html#finance")]
cd="".join(f'<a class="card" href="{u}"><div class="icon">{i}</div><h3>{t}</h3><p>{d}</p></a>' for i,t,d,u in cards)
home=f'''<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">TNAU · AC&amp;RI VAZHAVACHANUR</span><h1>GreenFarm.<br><span>Smarter farming.</span></h1><p>Simple digital tools for crops, livestock, farm activities and records.</p><div class="hero-actions"><a class="btn btn-gold" href="farm.html">Open Workspace</a><a class="btn btn-light" href="dashboard.html">Dashboard</a></div></div><div class="hero-panel"><strong>GreenFarm workspace</strong><div class="panel-grid"><div class="metric"><small>Modules</small><strong>13</strong></div><div class="metric"><small>Storage</small><strong>Local</strong></div><div class="metric"><small>Backup</small><strong>JSON</strong></div><div class="metric"><small>Reports</small><strong>PDF</strong></div></div></div></div></section><div class="container"><div class="snapshot-grid"><div class="snap"><strong>13</strong><span>Modules</span></div><div class="snap"><strong>Local</strong><span>Private data</span></div><div class="snap"><strong>Mobile</strong><span>Responsive</span></div><div class="snap"><strong>JSON</strong><span>Backup</span></div></div></div><section class="section"><div class="container"><div class="section-head"><span class="kicker">TOOLS</span><h2>Farm essentials</h2><p>Open a tool and start.</p></div><div class="modules">${cd}</div></div></section>'''
open("index.html","w").write(shell("index","Smart Digital Agriculture",home))
s=open("farm.html",encoding="utf-8").read(); m=re.search(r'<main class="farm-shell">.*?</main>',s,re.S)
if not m: raise SystemExit("farm main not found")
toast=re.search(r'<div class="toast"[^>]*>.*?</div>',s,re.S); tail=toast.group(0) if toast else '<div class="toast" id="toast" role="status"></div>'
open("farm.html","w").write(shell("farm","Workspace",m.group(0)+tail,'<script src="assets/farm.js"></script>'))
